modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0-only"
[[mods]]
modId="embeddium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium modified to run on Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"

[[mods]]
modId = "rubidium"
version = "0.2.12"
displayName = "Rubidium (Embeddium)"
description = '''
Stub, to allow mods detecting Rubidium to function as expected.
'''
