modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-only"
[[mods]]
modId="rubidium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium modified to run on Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"
