modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="embeddium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium with patches for Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"

[[dependencies.embeddium]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "[20.3,20.4)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[mods]]
modId = "rubidium"
version = "0.7.1"
displayName = "Rubidium (Embeddium)"
description = '''
Stub, to allow mods detecting Rubidium to function as expected.
'''
