modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="embeddium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium with patches for Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"

[[dependencies.embeddium]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
mandatory = true
versionRange = "[20.4.203,)" #mandatory
ordering = "NONE"
side = "CLIENT"

# Enforce new enough Oculus
[[dependencies.embeddium]]
modId = "oculus"
type = "optional"
mandatory = false
versionRange = "(1.6.15,)"
ordering = "BEFORE"
side = "CLIENT"

# The new config screen supersedes TexTrue's Embeddium Options
[[dependencies.embeddium]]
modId = "textrues_embeddium_options"
type = "optional"
versionRange = "[0.0.0-NOT-COMPATIBLE]"
ordering = "BEFORE"
side = "CLIENT"
