modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="embeddium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium with patches for Forge
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"

[[dependencies.embeddium]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[20.4.134-beta,)" #mandatory
ordering = "NONE"
side = "CLIENT"

# Enforce new enough Oculus
[[dependencies.embeddium]]
modId = "oculus"
type = "optional"
versionRange = "[1.6.15,)"
ordering = "BEFORE"
side = "CLIENT"
