modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
[[mods]]
modId="rubidium"
version="${version}"
displayName="Embeddium"
logoFile="icon.png"
description='''
Embeddium is a fork of Rubidium, a fork of Sodium with patches for Forge
'''
credits="NanoLive, Asek3"
authors="embeddedt, JellySquid"