modLoader="javafml"
loaderVersion="[39,)"
license="GPLv3"
[[mods]]
modId="rubidium"
version="0.4.0"
displayName="Rubidium"
logoFile="icon.png"
description='''
Rubidium is a Unofficial Fork of the Sodium maked to work on FML.
'''
credits="NanoLive, CaffeineMC"
authors="NanoLive"
